name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *'
    - cron: '0 0 1 4 *'
    - cron: '0 0 30 6 *'
    - cron: '0 0 28 9 *'
    - cron: '0 0 27 12 *'

jobs:
  macOS:
    env:
      PROCURSUS: /opt/procursus
      PATH: /opt/procursus/bin:/opt/procursus/libexec/gnubin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
    
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Build
        run: |
          ${{ github.workspace }}/.github/workflows/mac-bootstrap.sh
          ${{ github.workspace }}/.github/workflows/mac-build.sh
          ${{ github.workspace }}/.github/workflows/mac-post.sh

      - name: Upload versioning
        uses: actions/upload-artifact@v2
        with:
          name: Versioning
          path: |
            ${{ github.workspace }}/latest_build_sha.txt
            ${{ github.workspace }}/latest_build_num.txt

      - name: Upload x86_64-RELEASE
        uses: actions/upload-artifact@v2
        with:
          name: iBoot64Patcher-macOS-x86_64-RELEASE
          path: ${{ github.workspace }}/iBoot64Patcher-macOS-x86_64-*-RELEASE.tar.xz

      - name: Upload x86_64-DEBUG
        uses: actions/upload-artifact@v2
        with:
          name: iBoot64Patcher-macOS-x86_64-DEBUG
          path: ${{ github.workspace }}/iBoot64Patcher-macOS-x86_64-*-DEBUG.tar.xz

      - name: Upload arm64-RELEASE
        uses: actions/upload-artifact@v2
        with:
          name: iBoot64Patcher-macOS-arm64-RELEASE
          path: ${{ github.workspace }}/iBoot64Patcher-macOS-arm64-*-RELEASE.tar.xz

      - name: Upload arm64-DEBUG
        uses: actions/upload-artifact@v2
        with:
          name: iBoot64Patcher-macOS-arm64-DEBUG
          path: ${{ github.workspace }}/iBoot64Patcher-macOS-arm64-*-DEBUG.tar.xz

  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: debian:buster-slim
          options: -v ${{ github.workspace }}/..:/tmp/Builder/repos/
          run: |
            /tmp/Builder/repos/iBoot64Patcher/.github/workflows/linux-bootstrap.sh
            /tmp/Builder/repos/iBoot64Patcher/.github/workflows/linux-build.sh
            /tmp/Builder/repos/iBoot64Patcher/.github/workflows/linux-post.sh

      - name: Build x86_64-RELEASE
        run: |
          mkdir -p ${{ github.workspace }}/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/iBoot64Patcher/.github/workflows/name1.txt ${{ github.workspace }}/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/iBoot64Patcher/.github/workflows/iBoot64Patcher1.tar.xz ${{ github.workspace }}/.github/workflows/
          mv ${{ github.workspace }}/.github/workflows/iBoot64Patcher1.tar.xz ${{ github.workspace }}/.github/workflows/$(cat ${{ github.workspace }}/.github/workflows/name1.txt)

      - name: Build x86_64-DEBUG
        run: |
          mkdir -p ${{ github.workspace }}/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/iBoot64Patcher/.github/workflows/name2.txt ${{ github.workspace }}/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/iBoot64Patcher/.github/workflows/iBoot64Patcher2.tar.xz ${{ github.workspace }}/.github/workflows/
          mv ${{ github.workspace }}/.github/workflows/iBoot64Patcher2.tar.xz ${{ github.workspace }}/.github/workflows/$(cat ${{ github.workspace }}/.github/workflows/name2.txt)

      - name: Upload x86_64-RELEASE
        uses: actions/upload-artifact@v2
        with:
          name: iBoot64Patcher-Linux-x86_64-RELEASE
          path: ${{ github.workspace }}/.github/workflows/iBoot64Patcher-Linux-x86_64*-RELEASE.tar.xz

      - name: Upload x86_64-DEBUG
        uses: actions/upload-artifact@v2
        with:
          name: iBoot64Patcher-Linux-x86_64-DEBUG
          path: ${{ github.workspace }}/.github/workflows/iBoot64Patcher-Linux-x86_64*-DEBUG.tar.xz
